/**
 * CLIENTES
 * Funções de apoio para cadastro/listagem de clientes em versões modularizadas.
 */

function atualizarClientesLista(){const dl=$('clientesLista');dl.innerHTML='';dados.clientes.sort((a,b)=>a.nome.localeCompare(b.nome)).forEach(c=>{const o=document.createElement('option');o.value=c.nome;dl.appendChild(o);});}
function adicionarCliente(){const n=$('novoCliente').value.trim().toUpperCase(),t=$('telefoneCliente').value.trim(),cpf=$('cpfCliente').value.trim(),end=$('enderecoCliente').value.trim().toUpperCase();if(!n){toast('DIGITE O NOME');return;}if(encontrarCliente(n)){toast('CLIENTE JÁ EXISTE');return;}dados.clientes.push({id:'C'+Date.now(),nome:n,telefone:t,cpf,endereco:end});limparClienteForm();salvar();renderTudo();toast('CLIENTE ADICIONADO');}
function editarCliente(id){const c=dados.clientes.find(x=>x.id===id);if(!c)return;$('clienteEditandoId').value=id;$('novoCliente').value=c.nome;$('telefoneCliente').value=c.telefone||'';$('cpfCliente').value=c.cpf||'';$('enderecoCliente').value=c.endereco||'';$('btnAddCliente').style.display='none';$('btnSalvarCliente').style.display='block';$('btnCancelarCliente').style.display='block';toast('EDITANDO CLIENTE');}
function salvarEdicaoCliente(){const id=$('clienteEditandoId').value,c=dados.clientes.find(x=>x.id===id);if(!c)return;const antigo=c.nome,novo=$('novoCliente').value.trim().toUpperCase();if(!novo){toast('DIGITE O NOME');return;}c.nome=novo;c.telefone=$('telefoneCliente').value.trim();c.cpf=$('cpfCliente').value.trim();c.endereco=$('enderecoCliente').value.trim().toUpperCase();dados.vales.forEach(v=>{if(v.cliente===antigo){v.cliente=novo;v.telefone=c.telefone;v.cpf=c.cpf;v.endereco=c.endereco;}});salvar();cancelarEdicaoCliente();renderTudo();toast('CLIENTE ALTERADO');}
function limparClienteForm(){$('novoCliente').value='';$('telefoneCliente').value='';$('cpfCliente').value='';$('enderecoCliente').value='';}
function cancelarEdicaoCliente(){$('clienteEditandoId').value='';limparClienteForm();$('btnAddCliente').style.display='block';$('btnSalvarCliente').style.display='none';$('btnCancelarCliente').style.display='none';}
function renderClientes(){const q=($('buscaCliente').value||'').toUpperCase();const arr=dados.clientes.filter(c=>c.nome.includes(q)||String(c.telefone||'').includes(q)||String(c.cpf||'').includes(q)).sort((a,b)=>a.nome.localeCompare(b.nome));$('listaClientes').innerHTML=arr.length?arr.map(c=>`<div class="item"><div class="item-top"><h3>${htmlEsc(c.nome)}</h3></div><p>TELEFONE: <b>${htmlEsc(c.telefone||'NÃO INFORMADO')}</b><br>CPF: <b>${htmlEsc(c.cpf||'NÃO INFORMADO')}</b><br>ENDEREÇO: <b>${htmlEsc(c.endereco||'NÃO INFORMADO')}</b></p><div class="row-btns"><button onclick="usarCliente('${c.nome.replace(/'/g,"\\'")}')">USAR</button><button onclick="editarCliente('${c.id}')">EDITAR</button><button onclick="abrirWhatsAppCliente('${c.id}')">WHATSAPP</button><button onclick="excluirCliente('${c.id}')">EXCLUIR</button></div></div>`).join(''):'<div class="ajuda">NENHUM CLIENTE ENCONTRADO.</div>';}
function usarCliente(c){$('cliente').value=c;abrirTela('emprestimo');}
function excluirCliente(id){if(confirm('EXCLUIR CLIENTE?')){dados.clientes=dados.clientes.filter(x=>x.id!==id);salvar();renderTudo();}}
