function statusVale(v){if(v.status==='PAGO')return 'pago';const hoje=dataInput(new Date());return v.dataFinal<hoje?'atrasado':'aberto';}
function renderHistorico(){const q=($('buscaHistorico').value||'').toUpperCase();const lista=dados.vales.filter(v=>v.cliente.includes(q));$('qtdVales').textContent=dados.vales.length+' VALES';let emp=0,rec=0,ab=0;dados.vales.forEach(v=>{emp+=v.valor;rec+=v.total;if(v.status!=='PAGO')ab+=v.total;});$('statEmprestado').textContent=moeda(emp);$('statReceber').textContent=moeda(rec);$('statAberto').textContent=moeda(ab);$('listaHistorico').innerHTML=lista.length?lista.map(v=>{const s=statusVale(v),cad=encontrarCliente(v.cliente),tel=v.telefone||(cad?cad.telefone:'');return `<div class="item"><div class="item-top"><h3>${htmlEsc(v.cliente)}</h3><span class="status ${s}">${v.status==='PAGO'?'PAGO':s==='atrasado'?'ATRASADO':'ABERTO'}</span></div><p>TELEFONE: <b>${htmlEsc(tel||'NÃO INFORMADO')}</b><br>VALOR: <b>${moeda(v.valor)}</b><br>TOTAL: <b>${moeda(v.total)}</b><br>VENCIMENTO: ${dataBR(v.dataFinal)}<br>JUROS: ${String(v.juros).replace('.',',')}%</p><div class="row-btns"><button onclick="editarVale('${v.id}')">EDITAR</button><button onclick="reimprimir('${v.id}')">IMPRIMIR</button><button onclick="marcarPago('${v.id}')">${v.status==='PAGO'?'ABRIR':'RECEBIDO'}</button><button onclick="enviarValeHistorico('${v.id}')">ENVIAR PDF</button><button onclick="excluirVale('${v.id}')">EXCLUIR</button></div></div>`}).join(''):'<div class="ajuda">NENHUM VALE ENCONTRADO.</div>';}
function modoEdicao(ativo){$('btnAtualizar').style.display=ativo?'block':'none';$('btnCancelarEdicao').style.display=ativo?'block':'none';$('btnImprimir').style.display=ativo?'none':'block';document.querySelector('#emprestimo .sub').textContent=ativo?'EDITANDO VALE DO HISTÓRICO':'SISTEMA DE EMPRÉSTIMOS';}
function editarVale(id){const v=dados.vales.find(x=>x.id===id);if(!v){toast('VALE NÃO ENCONTRADO');return;}editandoId=id;$('cliente').value=v.cliente||'';$('valor').value=moeda(v.valor||0);$('juros').value=String(v.juros||0).replace('.',',')+'%';$('valorComTaxa').value=moeda(v.total||0);$('dataInicial').value=v.dataInicial||'';$('dataFinal').value=v.dataFinal||'';$('observacao').value=v.observacao||'';calcular();modoEdicao(true);abrirTela('emprestimo');toast('EDITE OS DADOS E SALVE');}
function atualizarValeEditado(){if(!editandoId){toast('NENHUM VALE EM EDIÇÃO');return;}const idx=dados.vales.findIndex(x=>x.id===editandoId);if(idx<0){toast('VALE NÃO ENCONTRADO');return;}const atual=dados.vales[idx],novo=novoVale(),erro=validarVale(novo);if(erro){toast(erro);return;}dados.vales[idx]={...atual,...novo,id:atual.id,status:atual.status,criadoEm:atual.criadoEm,editadoEm:new Date().toISOString()};garantirCliente(novo.cliente,novo.telefone,novo.cpf,novo.endereco);salvar();renderTudo();modoEdicao(false);editandoId=null;limparFormulario();abrirTela('historico');toast('VALE ALTERADO');}
function cancelarEdicao(){editandoId=null;modoEdicao(false);limparFormulario();toast('EDIÇÃO CANCELADA');}
function reimprimir(id){const v=dados.vales.find(x=>x.id===id);if(v)imprimirVale(v);}
function marcarPago(id){const v=dados.vales.find(x=>x.id===id);if(v){v.status=v.status==='PAGO'?'ABERTO':'PAGO';salvar();renderTudo();}}
function excluirVale(id){if(confirm('EXCLUIR ESTE VALE?')){dados.vales=dados.vales.filter(v=>v.id!==id);salvar();renderTudo();}}
